version: "3.7"
networks:
  app-net:
volumes:
  app-data:
  app-redis:
  app-caddy:

services:
  caddy:
    image: caddy
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./public:/srv/app/public
    ports:
      - "8100:80"
    networks:
      - app-net

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8099:80"
    volumes:
      - ./public:/srv/app/public
    networks:
      - app-net

  php:
    build:
      args:
        - PHP_VERSION=${PHP_VERSION}
      context: .
      dockerfile: .docker/php/Dockerfile
    user: "${UID}:${GID}"
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
    extra_hosts:
#      - "host.docker.internal:host-gateway"
      # host-gateway does not work on Linux with Traefik managing docker.sock
      - "host.docker.internal:172.20.0.1"
    depends_on:
      - mariadb
    ports:
      - "9000"
      - "9003" #Xdebug3
    volumes:
      - .:/srv/app
      - ./.profiler/:/tmp/xdebug/
      - ./.logs/:/logs/
    networks:
      - app-net
    env_file: .env

  # ------------------------
  # Databases
  # ------------------------
  mariadb:
    image: mariadb:10.5
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-net
    env_file: .env

  smtp:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
    networks:
#      - proxy
      - app-net

  redis:
    image: redis/redis-stack
    hostname: redis
    restart: on-failure
    ports:
      - '6379:6379'
      - '8026:8001'
    networks:
      app-net: